# theme: jekyll-theme-slate
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: ["ChemBFN: Bayesian Flow Network framework for Chemistry Tasks"]
description: ["Project blog"]
show_downloads: [false]